Models/Curso.cs
//conjunto de Classes

namespace AplicativoWeb.Models;

public class Curso
{

    public int Id { get; set; }
    public string? TituloMarketing { get; set; }

    public string? Titulointerno { get; set; }

    public string? Descricao { get; set; }

}

Models/ErrorViewModel.cs
namespace AplicativoWeb.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/CursoController.cs
using AplicativoWeb.Models;
using Microsoft.AspNetCore.Mvc; // microsoft
//conjunto de Classes



namespace AplicativoWeb.Controllers; // definição

public class CursoController:Controller{


        /*

        ações ou actions
        objetivo:Resirecionar para as paginas (web)

        */


        /*
            Interface = interface grafica
            Orientadoa a objtetos Interface é um contrato
        */
public IActionResult Index(){
    // encapsular é esconder, estudar encapsulamento no youtube de orientação a objeto
    
    Curso c1 = new Curso();
    // define o componente da função SET
    c1.Descricao       = "Primeiros Passos no Asp.NET core";
    c1.Titulointerno   = "Desenvolvedor C#";
    c1.TituloMarketing = "Crie Aplicativos Dinamicos";

    // define o componente da função GET
    
    
    ViewData["curso"] = c1; // passa o objeto para dentro do ViewData (c1 o objeto)
     
     return View();
    
}

public IActionResult Create(){

    ViewData["titulo"]="Cadastro de Cursos";
    ViewBag.DataHora = DateTime.Now;

    return View();





}


}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AplicativoWeb.Models;

namespace Aplicativoweb.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Curso/Create.cshtml
<h1>@ViewData["titulo"]</h1>
<h6>@ViewBag.DataHora</h6>

<div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Titulo Interno</label>
  <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="">
</div>
<div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Titulo de Marketing</label>
  <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="">
</div>
<div class="mb-3">
  <label for="exampleFormControlTextarea1" class="form-label">Descrição</label>
  <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
</div>

<button type="button" class="btn btn-primary" data-bs-toggle="button" autocomplete="off">Buscar</button>
<button type="button" class="btn btn-primary active" data-bs-toggle="button" autocomplete="off" aria-pressed="true">Cadastrar</button>
<button type="button" class="btn btn-primary" disabled data-bs-toggle="button" autocomplete="off">Cancelar</button>

Views/Curso/Index.cshtml
@{


  var curso = ViewData["curso"] as Curso; // converte



}


<div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
  <div class="card-header">@curso?.Titulointerno</div>
  <div class="card-body">
    <h5 class="card-title">@curso?.TituloMarketing</h5>
    <p class="card-text">@curso?.Descricao</p>
  </div>
</div>


<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="..." class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">@curso?.Titulointerno</h5>
        <p class="card-text">@curso?.TituloMarketing</p>
        <p class="card-text">@curso?.Descricao<small class="text-muted"></small></p>
      </div>
    </div>
  </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aplicativoweb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Aplicativoweb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Aplicativoweb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>   <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Curso" asp-action="Index">Cursos</a>   <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Curso" asp-action="Create">Criar</a>   <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Curso" asp-action="Index">Novo Curso</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Aplicativoweb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>